# Server Configuration
do_region: "lon1" # London region
do_size: "s-1vcpu-2gb-amd" # Basic AMD with 1GB RAM
do_image: "ubuntu-24-04-x64" # Ubuntu 24.04 LTS
do_monitoring: true # Enable DigitalOcean monitoring/metrics

# DigitalOcean Configuration
do_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
do_ssh_keys: "{{ lookup('env', 'DO_SSH_KEYS') | split(',') }}"
server_user: "{{ lookup('env', 'SERVER_USERNAME') }}"
root_password: "{{ lookup('env', 'ROOT_PASSWORD') }}"

# Apps Configuration
apps_user: "{{ server_user }}"
apps_group: "{{ server_user }}"
apps_base_dir: "/opt"
compose_command: "docker compose"

server_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - tmux
  - git
  - nano

# UFW Configuration
ufw_rules:
  - { port: "80", proto: "tcp" }
  - { port: "443", proto: "tcp" }
  - { port: "22", proto: "tcp" }

# Tmux Configuration
tmux_config_repo: "https://github.com/gpakosz/.tmux.git"
