all:
  children:
    digitalocean:
      hosts:
      vars:
        # Don't set ansible_user here as it needs to be root initially
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
