---
# Reusable tasks for loading environment variables from .env file
# Include this in playbooks that need .env support

- name: Check if .env file exists
  stat:
    path: "{{ playbook_dir }}/../.env"
  register: env_file
  delegate_to: localhost
  become: false

- name: Load environment variables from .env file
  shell: |
    grep -v '^#' {{ playbook_dir }}/../.env | grep -v '^$'
  register: env_vars
  when: env_file.stat.exists
  changed_when: false
  delegate_to: localhost
  become: false

- name: Set environment variables as facts
  set_fact:
    "{{ item.split('=')[0] }}": "{{ item.split('=', 1)[1] }}"
  loop: "{{ env_vars.stdout_lines | default([]) }}"
  when: env_file.stat.exists and '=' in item
  no_log: true
