---
- name: Create proxy network
  docker_network:
    name: "{{ caddy_network_name }}"
    driver: bridge

- name: Create Caddy data volume
  docker_volume:
    name: "{{ caddy_data_volume }}"

- name: Create Caddy config volume
  docker_volume:
    name: "{{ caddy_config_volume }}"

- name: Stop existing Caddy container if running
  docker_container:
    name: "{{ caddy_container_name }}"
    state: absent
    force_kill: yes

- name: Start Caddy Docker Proxy container
  docker_container:
    name: "{{ caddy_container_name }}"
    image: "{{ caddy_image }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ caddy_network_name }}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ caddy_data_volume }}:/data"
      - "{{ caddy_config_volume }}:/config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      CADDY_INGRESS_NETWORKS: "{{ caddy_network_name }}"
      CADDY_DOCKER_LABEL_PREFIX: "caddy"
      CADDY_ACME_AGREE: "true"
      CADDY_EMAIL: "{{ caddy_email }}"
    labels:
      caddy_docker_proxy: "true"

- name: Wait for Caddy to be ready
  wait_for:
    port: 80
    host: "{{ ansible_default_ipv4.address }}"
    delay: 5
    timeout: 60

- name: Display Caddy proxy status
  debug:
    msg: |
      ✅ Caddy Docker Proxy is running!
      - Container: {{ caddy_container_name }}
      - Network: {{ caddy_network_name }}
      - Image: {{ caddy_image }}
      - Health endpoint: http://{{ ansible_default_ipv4.address }}:2019/health
      - Data volume: {{ caddy_data_volume }}
      - Config volume: {{ caddy_config_volume }}
